version: '3.8'
services:
  server:
    # command: poetry run python db.py -t al
    build: ./backend
    command: poetry run python app.py
    env_file:
      - ./backend/.env
    ports:
      - 8000:5000
    links:
      - migration
    networks: 
      - backend_network
      
  migration:
    build: ./backend
    env_file:
      - ./backend/.env
    command: poetry run python db.py -t all
    depends_on:
      - db
    networks:
      - backend_network
# database name
  db:
    image: mariadb:latest
    volumes:
      - ${PWD}/database:/var/lib/mysql/
    env_file:
      - ./backend/.env
    ports:
      - 3306:3306
    networks:
      - backend_network


volumes:
  mariadb_data:
  
networks: 
  backend_network: